# https://rust-lang.github.io/rustup-components-history/
[toolchain]
channel = "nightly-2026-05-08"
components = [
	"rustc",
	"rust-std",
	"cargo",
	"clippy",
	"rustfmt",
]
targets = [
	"x86_64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-msvc",
	"aarch64-unknown-linux-gnu",
	"aarch64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"aarch64-pc-windows-msvc",
	"riscv64gc-unknown-linux-gnu",
	"riscv64gc-unknown-linux-musl",
	"riscv64a23-unknown-linux-gnu",
]